services:
  api:
    build: ./backend
    container_name: nexas_api
    ports:
      - "5001:8080"
    networks:
      - agivys_default
    restart: unless-stopped

  landing:
    build: ./frontend/landing
    container_name: nexas_landing
    ports:
      - "4200:80"
    networks:
      - agivys_default
    restart: unless-stopped

  portal-pan:
    build: ./frontend/portal-pan
    container_name: nexas_portal
    ports:
      - "4205:80"
    networks:
      - agivys_default
    restart: unless-stopped

networks:
  agivys_default:
    external: true
