version: '3.8'

services:
  # Banco de Dados MySQL
  mysql_banco:
    image: mysql:8.0
    container_name: nexas-mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Likeaboos1970
      MYSQL_DATABASE: nexas_bd
    ports:
      - "3317:3306"
    volumes:
      - nexas_db_data:/var/lib/mysql
    networks:
      - nexas-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pLikeaboos1970"]
      timeout: 20s
      retries: 10

  # 1. Nexas.Lemon.Admin.Api - Porta 5012
  Nexas.Lemon.Admin.Api:
    build:
      context: .
      dockerfile: Nexas.Lemon.Admin.Api/Dockerfile
    container_name: Nexas.Lemon.Admin.Api-container
    ports:
      - "6012:8080"
    env_file:
      - .env
    depends_on:
      mysql_banco:
        condition: service_healthy
    networks:
      - nexas-network
      - agivys_default
    restart: always

  # 2. Nexas.Lemon.Ead.Api (PAN) - Porta 5011
  Nexas.Lemon.Ead.Api:
    build:
      context: .
      dockerfile: Nexas.Lemon.Ead.Api/Dockerfile
    container_name: Nexas.Lemon.Ead.Api-container
    ports:
      - "6011:8080"
    env_file:
      - .env
    depends_on:
      mysql_banco:
        condition: service_healthy
    networks:
      - nexas-network
      - agivys_default
    restart: always

  # 3. Nexas.Lemon.Landing.Api - Porta 5013
  Nexas.Lemon.Landing.Api:
    build:
      context: .
      dockerfile: Nexas.Lemon.Landing.Api/Dockerfile
    container_name: Nexas.Lemon.Landing.Api-container
    ports:
      - "6013:8080"
    env_file:
      - .env
    depends_on:
      mysql_banco:
        condition: service_healthy
    networks:
      - nexas-network
      - agivys_default
    restart: always

  # 4. Nexas System Manager API - Porta 6014
  nexas-system-manager-api:
    build:
      context: .
      dockerfile: Nexas.SystemManager/Dockerfile
    container_name: nexas-system-manager-api-container
    ports:
      - "6014:8080"
    env_file:
      - .env
    depends_on:
      mysql_banco:
        condition: service_healthy
    networks:
      - nexas-network
      - agivys_default
    restart: always

networks:
  nexas-network:
    driver: bridge
  agivys_default:
    external: true

volumes:
  nexas_db_data:
